### ISSUE TITLE
Map Content

### ISSUE THREAD

**Issue by OathOfIsaac** [OathOfIsaac/Fetch#7]
## Requirements

-Research Map API and insert source code into html
- local Storage Client Adresses
- Create "Walk!" button
-Pull nearest client adress on event, create map route for walk
-  Create HTML effiecient way to customize walk lengths (UI Friendly)
-Randomize Walks based on walk length

**Comment by JTM1220** [comment]
Found Map API https://leafletjs.com/SlavaUkraini/examples/quick-start/

Was unable to use google maps API as they require a credit card RIP!
